name: Beta deploy to Cocoapods

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  deploy-cocoapods-beta:
    name: Beta deploy to Cocoapods
    runs-on: macOS-latest
    if: startsWith(github.ref, 'refs/heads/beta-release/')
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout source branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Publish to CocoaPod
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push --allow-warnings